logstash:
    build: logstash-contrib
    volumes:
        - logstash-contrib:/config/
    command: logstash -f /config/logstash.conf
    ports:
        - "25826:25826"
    links:
        - elasticsearch

kibana:
    build: kibana
    links:
        - elasticsearch
    ports:
        - "5601:5601"

elasticsearch:
    image: elasticsearch
